frr defaults traditional
hostname frr-h2
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 2.2.2.2/32
exit
!
router ospf
 network 2.2.2.2/32 area 0
 network 10.10.10.0/24 area 0
 network 20.20.20.0/24 area 0
exit
!
